---
title: "Formative Test Visualization"
author: "HUDK4050"
date: "11/9/2017"
output: html_document
---


```{r, echo=FALSE}
#Input your data processing steps here

#Name your first data frame "D1" 

D1<-formative1_results_DI

```

## Example Visualization Name
```{r, echo=FALSE}
#Create a new code block, give it an appropriate title and input your visualization code.

```

```{r}
D1$pull.request <- NULL
D1$attached.rmd <- NULL
```

```{r}
D2<-data.frame(ifelse(D1 == "Yes",1,0))
```

```{r}
R2<-data.frame(ifelse(D1 == "No",1,0))
```

```{r}
B2<-data.frame(ifelse(D1 == "Did not answer",1,0))
```

```{r}
D2[is.na(D2)]<-0
```

```{r}
R2[is.na(R2)]<-0
```

```{r}
B2[is.na(B2)]<-0
```

```{r}
D3<-colSums(D2)
```

```{r}
R3<-colSums(R2)
```

```{r}
B3<-colSums(B2)
```

```{r}
df <- data.frame(B3,D3, R3)
B3_name <- "Did not answer"
D3_name <- "Yes"
R3_name <- "No"
names(df) <- c(B3_name,D3_name, R3_name)
```

```{r}

# Compute the largest y value used in the data (or we could
# just use range again)
max_y <- max(df)

# Define colors to be used for cars, trucks, suvs
plot_colors <- c("blue","forestgreen","red")


# Graph autos using y axis that ranges from 0 to max_y.
# Turn off axes and annotations (axis labels) so we can 
# specify them ourself
plot(df$"Did not answer", type="o", col=plot_colors[1], 
   ylim=c(0,max_y), axes=FALSE, ann=FALSE)

# Make x axis using Mon-Fri labels
axis(1, at=1:14, lab=c("Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "Q9", "Q10", "Q11", "Q12", "Q13", "Q14"))

# Make y axis with horizontal labels that display ticks at 
# every 4 marks. 4*0:max_y is equivalent to c(0,4,8,12).
axis(2, las=1, at=4*0:max_y)

# Create box around plot
box()

# Graph trucks with red dashed line and square points
lines(df$Yes, type="o", pch=22, lty=2, 
   col=plot_colors[2])

# Graph suvs with green dotted line and diamond points
lines(df$No, type="o", pch=23, lty=3, 
   col=plot_colors[3])

# Create a title with a red, bold/italic font
title(main="Test", col.main="red", font.main=4)

# Label the x and y axes with dark green text
title(xlab= "Questions", col.lab=rgb(0,0.5,0))
title(ylab= "# of responses", col.lab=rgb(0,0.5,0))

# Create a legend at (1, max_y) that is slightly smaller 
# (cex) and uses the same line colors and points used by 
# the actual plots
legend(1, max_y, names(df), cex=0.8, col=plot_colors, 
   pch=21:23, lty=1:3);
```
```{r}
#Did not answer #Yes #No
library(dplyr)
piechart<-c(sum(select(B2,Q9)),sum(select(D2,Q9)),sum(select(R2,Q9)))
pie(piechart, main="Questions 9", col=rainbow(length(piechart)),
   labels=c("Did not answer","Yes","No"))

```
```{r}
#boxplot(D4, main="Class Percentage",xlab="Students",ylab="Test Percentage")
```
```{r}
barplot(t(df), main="Student Response of Formative Test 1",
  xlab="Questions", ylab= "# of responses", col=c("violet","yellow", "turquoise"), legend = colnames(df))
```




```

